services:
  redis:
    image: redis:latest
    container_name: redisCloud
    ports:
      - "6379:6379"
    networks:
      - first_network
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmqCloud
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - first_network

networks:
    first_network:
