version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redisCloud
    ports:
      - "6379:6379"
    networks:
      - first_network
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmqCloud
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - first_network
  gateway-service:
    image: aliaksandrshydlouski/gateway-service:1.0
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - first_network
  cloud-service:
    image: aliaksandrshydlouski/cloud-service:1.0
    container_name: cloud-service
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - rabbitmq
    networks:
        - first_network


  notifications-service:
    image: aliaksandrshydlouski/notification-service:1.0
    container_name: notifications-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
        - "8082:8082"
    networks:
        - first_network
    depends_on:
      - cloud-service

networks:
  first_network:
   